<a href="https://colab.research.google.com/github/sanagahoi/log-classifier/blob/main/Log_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version

Python 3.11.3

In [2]:
import pandas as pd

df = pd.read_csv("synthetic_logs.csv")
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     2410 non-null   object
 1   source        2410 non-null   object
 2   log_message   2410 non-null   object
 3   target_label  2410 non-null   object
 4   complexity    2410 non-null   object
dtypes: object(5)
memory usage: 94.3+ KB

In [4]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [5]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [7]:
!pip install sentence-transformers

Collecting sentence-transformers

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 4.0.2 requires pydantic>=2.0, but you have pydantic 1.10.13 which is incompatible.
gradio 4.0.2 requires websockets<12.0,>=10.0, but you have websockets 16.0 which is incompatible.
gradio-client 0.7.0 requires websockets<12.0,>=10.0, but you have websockets 16.0 which is incompatible.

  Downloading sentence_transformers-5.5.1-py3-none-any.whl.metadata (18 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.8.1-py3-none-any.whl.metadata (33 kB)
Collecting huggingface-hub>=0.23.0 (from sentence-transformers)
  Downloading huggingface_hub-1.15.0-py3-none-any.whl.metadata (14 kB)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.12.0-cp311-cp311-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: numpy>=1.20.0 in C:\Users\pc\anaconda3\Lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in C:\Users\pc\anaconda3\Lib\site-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in C:\Users\pc\anaconda3\Lib\site-packages (from sentence-transformers) (1.10.1)
Requirement already satisfied: typing_extensions>=4.5.0 in C:\Users\pc\anaconda3\Lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in C:\Users\pc\anaconda3\Lib\site-packages (from sentence-transformers) (4.65.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\pc\anaconda3\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (23.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\pc\anaconda3\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading regex-2026.5.9-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in C:\Users\pc\anaconda3\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.20.0)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting filelock>=3.10.0 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\pc\anaconda3\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2023.12.2)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub>=0.23.0->sentence-transformers)
  Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\pc\anaconda3\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.26.0)
Requirement already satisfied: anyio in C:\Users\pc\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.5.0)
Requirement already satisfied: certifi in C:\Users\pc\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in C:\Users\pc\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.2)
Requirement already satisfied: idna in C:\Users\pc\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.4)
Requirement already satisfied: sniffio in C:\Users\pc\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.2.0)
Requirement already satisfied: h11<0.15,>=0.13 in C:\Users\pc\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.14.0)
Requirement already satisfied: joblib>=1.1.1 in C:\Users\pc\anaconda3\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in C:\Users\pc\anaconda3\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.1.0)
Requirement already satisfied: setuptools<82 in C:\Users\pc\anaconda3\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (67.8.0)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\pc\anaconda3\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (2.8.4)
Requirement already satisfied: jinja2 in C:\Users\pc\anaconda3\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\pc\anaconda3\Lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.2.1)
Requirement already satisfied: colorama in C:\Users\pc\anaconda3\Lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: click>=8.0.0 in C:\Users\pc\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.1.3)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\pc\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in C:\Users\pc\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\pc\anaconda3\Lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\pc\anaconda3\Lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in C:\Users\pc\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\pc\anaconda3\Lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.1)
Downloading sentence_transformers-5.5.1-py3-none-any.whl (588 kB)
   ---------------------------------------- 0.0/588.9 kB ? eta -:--:--
   ---------------------------------------- 588.9/588.9 kB 7.0 MB/s  0:00:00
Downloading transformers-5.8.1-py3-none-any.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   --------- ------------------------------ 2.6/10.6 MB 11.6 MB/s eta 0:00:01
   ---------------- ----------------------- 4.5/10.6 MB 10.8 MB/s eta 0:00:01
   ------------------------ --------------- 6.6/10.6 MB 10.3 MB/s eta 0:00:01
   ------------------------------ --------- 8.1/10.6 MB 9.3 MB/s eta 0:00:01
   ----------------------------------- ---- 9.4/10.6 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------  10.5/10.6 MB 8.2 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 7.5 MB/s  0:00:01
Downloading huggingface_hub-1.15.0-py3-none-any.whl (663 kB)
   ---------------------------------------- 0.0/663.6 kB ? eta -:--:--
   ---------------------------------------- 663.6/663.6 kB 3.7 MB/s  0:00:00
Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/4.0 MB 5.6 MB/s eta 0:00:01
   -------------------------- ------------- 2.6/4.0 MB 6.9 MB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 6.3 MB/s  0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ------------------- -------------------- 1.3/2.7 MB 8.4 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 6.9 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 5.9 MB/s  0:00:00
Downloading filelock-3.29.0-py3-none-any.whl (39 kB)
Downloading regex-2026.5.9-cp311-cp311-win_amd64.whl (278 kB)
Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Downloading torch-2.12.0-cp311-cp311-win_amd64.whl (123.0 MB)
   ---------------------------------------- 0.0/123.0 MB ? eta -:--:--
    --------------------------------------- 1.6/123.0 MB 7.6 MB/s eta 0:00:16
   - -------------------------------------- 3.7/123.0 MB 9.1 MB/s eta 0:00:14
   -- ------------------------------------- 6.3/123.0 MB 9.9 MB/s eta 0:00:12
   -- ------------------------------------- 8.4/123.0 MB 9.8 MB/s eta 0:00:12
   --- ------------------------------------ 10.2/123.0 MB 9.8 MB/s eta 0:00:12
   --- ------------------------------------ 11.8/123.0 MB 9.3 MB/s eta 0:00:12
   ---- ----------------------------------- 14.2/123.0 MB 9.4 MB/s eta 0:00:12
   ----- ---------------------------------- 16.5/123.0 MB 9.6 MB/s eta 0:00:12
   ----- ---------------------------------- 18.4/123.0 MB 9.4 MB/s eta 0:00:12
   ------ --------------------------------- 20.2/123.0 MB 9.4 MB/s eta 0:00:11
   ------- -------------------------------- 22.0/123.0 MB 9.3 MB/s eta 0:00:11
   ------- -------------------------------- 23.9/123.0 MB 9.3 MB/s eta 0:00:11
   -------- ------------------------------- 26.0/123.0 MB 9.3 MB/s eta 0:00:11
   --------- ------------------------------ 28.0/123.0 MB 9.4 MB/s eta 0:00:11
   --------- ------------------------------ 30.1/123.0 MB 9.5 MB/s eta 0:00:10
   ---------- ----------------------------- 32.2/123.0 MB 9.4 MB/s eta 0:00:10
   ----------- ---------------------------- 34.3/123.0 MB 9.5 MB/s eta 0:00:10
   ----------- ---------------------------- 35.9/123.0 MB 9.4 MB/s eta 0:00:10
   ------------ --------------------------- 37.7/123.0 MB 9.3 MB/s eta 0:00:10
   ------------ --------------------------- 39.8/123.0 MB 9.4 MB/s eta 0:00:09
   ------------- -------------------------- 40.9/123.0 MB 9.2 MB/s eta 0:00:09
   ------------- -------------------------- 42.2/123.0 MB 9.0 MB/s eta 0:00:09
   -------------- ------------------------- 43.8/123.0 MB 8.9 MB/s eta 0:00:09
   --------------- ------------------------ 46.1/123.0 MB 9.0 MB/s eta 0:00:09
   --------------- ------------------------ 48.5/123.0 MB 9.1 MB/s eta 0:00:09
   ---------------- ----------------------- 50.3/123.0 MB 9.0 MB/s eta 0:00:09
   ---------------- ----------------------- 51.6/123.0 MB 8.9 MB/s eta 0:00:08
   ----------------- ---------------------- 53.5/123.0 MB 8.9 MB/s eta 0:00:08
   ------------------ --------------------- 55.6/123.0 MB 8.9 MB/s eta 0:00:08
   ------------------ --------------------- 58.2/123.0 MB 9.0 MB/s eta 0:00:08
   ------------------- -------------------- 60.3/123.0 MB 9.0 MB/s eta 0:00:07
   -------------------- ------------------- 62.4/123.0 MB 9.0 MB/s eta 0:00:07
   -------------------- ------------------- 63.7/123.0 MB 9.0 MB/s eta 0:00:07
   --------------------- ------------------ 65.5/123.0 MB 8.9 MB/s eta 0:00:07
   ---------------------- ----------------- 67.6/123.0 MB 8.9 MB/s eta 0:00:07
   ---------------------- ----------------- 70.0/123.0 MB 9.0 MB/s eta 0:00:06
   ----------------------- ---------------- 72.4/123.0 MB 9.0 MB/s eta 0:00:06
   ------------------------ --------------- 74.4/123.0 MB 9.1 MB/s eta 0:00:06
   ------------------------ --------------- 76.0/123.0 MB 9.0 MB/s eta 0:00:06
   ------------------------- -------------- 78.1/123.0 MB 9.0 MB/s eta 0:00:05
   -------------------------- ------------- 80.2/123.0 MB 9.0 MB/s eta 0:00:05
   -------------------------- ------------- 82.6/123.0 MB 9.1 MB/s eta 0:00:05
   --------------------------- ------------ 84.1/123.0 MB 9.0 MB/s eta 0:00:05
   --------------------------- ------------ 85.7/123.0 MB 9.0 MB/s eta 0:00:05
   ---------------------------- ----------- 87.3/123.0 MB 9.0 MB/s eta 0:00:04
   ----------------------------- ---------- 89.7/123.0 MB 9.0 MB/s eta 0:00:04
   ------------------------------ --------- 92.3/123.0 MB 9.0 MB/s eta 0:00:04
   ------------------------------ --------- 94.4/123.0 MB 9.0 MB/s eta 0:00:04
   ------------------------------- -------- 96.2/123.0 MB 9.0 MB/s eta 0:00:03
   ------------------------------- -------- 98.3/123.0 MB 9.1 MB/s eta 0:00:03
   -------------------------------- ------- 100.1/123.0 MB 9.0 MB/s eta 0:00:03
   --------------------------------- ------ 102.0/123.0 MB 9.0 MB/s eta 0:00:03
   ---------------------------------- ----- 104.6/123.0 MB 9.1 MB/s eta 0:00:03
   ---------------------------------- ----- 106.7/123.0 MB 9.1 MB/s eta 0:00:02
   ----------------------------------- ---- 108.5/123.0 MB 9.1 MB/s eta 0:00:02
   ----------------------------------- ---- 110.4/123.0 MB 9.0 MB/s eta 0:00:02
   ------------------------------------ --- 112.2/123.0 MB 9.0 MB/s eta 0:00:02
   ------------------------------------- -- 114.0/123.0 MB 9.0 MB/s eta 0:00:01
   ------------------------------------- -- 115.3/123.0 MB 9.0 MB/s eta 0:00:01
   -------------------------------------- - 116.9/123.0 MB 9.0 MB/s eta 0:00:01
   -------------------------------------- - 118.5/123.0 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  120.1/123.0 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  120.8/123.0 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------  121.6/123.0 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------  122.9/123.0 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------  122.9/123.0 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------  122.9/123.0 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------- 123.0/123.0 MB 8.3 MB/s  0:00:14
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Installing collected packages: sympy, safetensors, regex, hf-xet, filelock, torch, huggingface-hub, tokenizers, transformers, sentence-transformers

  Attempting uninstall: sympy

    Found existing installation: sympy 1.11.1

   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
    Uninstalling sympy-1.11.1:
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
      Successfully uninstalled sympy-1.11.1
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]
   ----------------------------------------  0/10 [sympy]

In [8]:
# all different patterns to use regex e.g. kmeans clustering and DBScan
# here we're using DBScan and SentenceTransformer

from sentence_transformers import SentenceTransformer, util
from sklearn.cluster import DBSCAN

model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(df['log_message'].tolist())

embeddings

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

array([[-0.10293962,  0.03354593, -0.02202606, ...,  0.00457791,
        -0.04259717,  0.00322621],
       [ 0.00804573, -0.03573923,  0.04938737, ...,  0.01538319,
        -0.06230948, -0.02774663],
       [-0.00908223,  0.13003924, -0.05275566, ...,  0.02014104,
        -0.05117098, -0.02930296],
       ...,
       [-0.04022264,  0.0422436 , -0.06610421, ...,  0.0236367 ,
        -0.00530877,  0.0204446 ],
       [-0.03603452,  0.01960893,  0.10052755, ...,  0.03668106,
        -0.02487851, -0.00578846],
       [ 0.01457431,  0.04911832, -0.00301354, ...,  0.01029741,
        -0.00068493,  0.00708859]], dtype=float32)

In [9]:
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
dbscan.fit(embeddings)

df['cluster'] = dbscan.labels_
df.head()

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [10]:
 # check some values - by custom values of hyper parameters we get cluster 1 for similar msgs

df[df.cluster==1]

,timestamp,source,log_message,target_label,complexity,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,bert,1
248,5/2/2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,bert,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,bert,1
361,11/19/2025 23:06,BillingSystem,Email service experienced a sending issue,Error,bert,1
450,10/27/2025 5:59,ThirdPartyAPI,Email delivery system encountered an error,Error,bert,1
477,12/2/2025 10:30,AnalyticsEngine,Email transmission error caused service impact,Critical Error,bert,1
570,11/7/2025 18:08,ThirdPartyAPI,Email service impacted by sending failure,Critical Error,bert,1
678,4/28/2025 15:13,AnalyticsEngine,Email delivery problem affected system,Critical Error,bert,1
695,6/30/2025 12:46,ThirdPartyAPI,Service outage due to email delivery problem,Critical Error,bert,1
816,7/9/2025 9:38,BillingSystem,Error in email delivery affected service,Critical Error,bert,1
926,2/17/2025 8:01,ModernCRM,Email service suffered a delivery failure,Error,bert,1
1011,2/9/2025 17:04,AnalyticsEngine,Error in email sending impacted service,Critical Error,bert,1
1018,2/16/2025 15:02,BillingSystem,Mail service impacted by delivery glitch,Critical Error,bert,1
1046,11/26/2025 22:54,AnalyticsEngine,Email service had a difficulty delivering mess...,Error,bert,1
1058,10/24/2025 5:37,AnalyticsEngine,Email system failed to deliver emails,Error,bert,1
1082,5/17/2025 11:20,ModernHR,Delivery failure impacted email services,Critical Error,bert,1
1151,6/17/2025 15:13,ThirdPartyAPI,Mail service was unable to send emails,Error,bert,1
1176,10/1/2025 12:27,AnalyticsEngine,Email provider faced a delivery challenge,Error,bert,1
1189,2/9/2025 6:15,ModernCRM,Service issue caused by email delivery error,Critical Error,bert,1
1359,8/18/2025 15:58,ModernCRM,Email system down due to sending error,Critical Error,bert,1
1414,6/22/2025 23:07,ModernCRM,Email system encountered a sending error,Error,bert,1
1427,10/26/2025 20:25,ModernHR,Email provider had trouble sending emails,Error,bert,1
1453,9/11/2025 1:18,BillingSystem,Mail delivery error impacted email service,Critical Error,bert,1
1554,3/2/2025 9:21,ModernCRM,Email system had a difficulty sending messages,Error,bert,1
1567,5/11/2025 11:17,ThirdPartyAPI,Email system affected by delivery failure,Critical Error,bert,1
1582,9/10/2025 9:27,BillingSystem,Email delivery failure resulted in service issue,Critical Error,bert,1
1860,6/26/2025 1:08,BillingSystem,Email provider experienced a mail delivery issue,Error,bert,1
1867,10/6/2025 11:04,ModernCRM,Email service had a sending malfunction,Error,bert,1
1901,9/22/2025 2:52,ThirdPartyAPI,Email service experienced a mail sending issue,Error,bert,1
1972,3/12/2025 3:48,ThirdPartyAPI,Delivery issue with email service caused outage,Critical Error,bert,1
2049,10/1/2025 22:07,AnalyticsEngine,Email server experienced a delivery problem,Error,bert,1
2165,4/4/2025 16:11,ThirdPartyAPI,Email server had trouble transmitting emails,Error,bert,1
2281,3/23/2025 20:12,ThirdPartyAPI,Mail delivery issue caused service disruption,Critical Error,bert,1
2284,10/4/2025 18:15,BillingSystem,Email service down due to transmission issue,Critical Error,bert,1
2312,3/9/2025 21:16,ModernHR,Email service faced a delivery obstacle,Error,bert,1
2340,3/26/2025 8:10,ModernCRM,Service outage due to email transmission error,Critical Error,bert,1
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1

In [11]:
cluster_counts = df['cluster'].value_counts()
large_clusters = cluster_counts[cluster_counts>10].index

for cluster in large_clusters:
    print(f"Cluster {cluster}:")
    print(df[df['cluster'] == cluster]['log_message'].head().to_string(index= False))
    print()

Cluster 0:
nova.osapi_compute.wsgi.server [req-b9718cd8-f6...
nova.osapi_compute.wsgi.server [req-4895c258-b2...
nova.osapi_compute.wsgi.server [req-ee8bc8ba-92...
nova.osapi_compute.wsgi.server [req-f0bffbc3-5a...
nova.osapi_compute.wsgi.server [req-2bf7cfee-a2...

Cluster 5:
nova.compute.claims [req-a07ac654-8e81-416d-bfb...
nova.compute.claims [req-d6986b54-3735-4a42-907...
nova.compute.claims [req-72b4858f-049e-49e1-b31...
nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a...
nova.compute.claims [req-d38f479d-9bb9-4276-968...

Cluster 11:
User User685 logged out.
 User User395 logged in.
 User User225 logged in.
User User494 logged out.
 User User900 logged in.

Cluster 13:
Backup started at 2025-05-14 07:06:55.
Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
Backup started at 2025-11-14 08:27:43.
Backup started at 2025-12-09 10:19:11.

Cluster 7:
Multiple bad login attempts detected on user 85...
Multiple login failures occurred on user 9052 a...
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
Multiple login failures were detected for user ...

Cluster 8:
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.

Cluster 21:
System updated to version 3.9.1.
System updated to version 5.5.4.
System updated to version 4.7.4.
System updated to version 3.7.7.
System updated to version 2.6.2.

Cluster 3:
         Shard 6 replication task ended in failure
Data replication task for shard 14 did not comp...
         Data replication task failed for shard 17
            Replication of data to shard 14 failed
Data replication task for shard 6 did not complete

Cluster 4:
File data_6169.csv uploaded successfully by use...
File data_3847.csv uploaded successfully by use...
File data_7366.csv uploaded successfully by use...
File data_1206.csv uploaded successfully by use...
File data_1503.csv uploaded successfully by use...

Cluster 17:
Denied access attempt on restricted account Acc...
Unauthorized login attempt on protected account...
   Account Account9437 blocked due to failed login
Account Account7999 access denied due to login ...
Invalid login attempt made on secured account A...

Cluster 32:
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.

Cluster 6:
   Critical system unit error: unit ID Component55
System component malfunction: component ID Comp...
Critical system element is down: element ID Com...
Essential system part malfunction: part ID Comp...
Failure occurred in critical system component: ...

Cluster 16:
System reboot initiated by user User243.
System reboot initiated by user User471.
System reboot initiated by user User216.
System reboot initiated by user User639.
System reboot initiated by user User819.

Cluster 20:
   User 7662 tried to bypass API security measures
User 2367 failed to provide valid API access cr...
        User 3569 made an unauthorized API request
Unauthorized user 2968 tried to access restrict...
User 2186 attempted to access API without prope...

Cluster 9:
Account with ID 5351 created by User634.
Account with ID 7813 created by User373.
Account with ID 9827 created by User965.
Account with ID 2520 created by User546.
Account with ID 2300 created by User964.

Cluster 1:
  Email service experiencing issues with sending
        Email server encountered a sending fault
      Mail service encountered a delivery glitch
Service disruption caused by email sending error
       Email system had a problem sending emails

Cluster 10:
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...

Cluster 34:
Abnormal behavior found on server 10, possible ...
   Security alert: suspicious activity on server 1
Anomalous activity identified on server 23, sec...
Server 27 experienced potential security incide...
Server 36 experienced potential security incide...

Cluster 14:
   Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
      RAID array experienced multiple disk crashes
Multiple hard drive issues in RAID configuratio...
Identification of multiple faulty disks in RAID...

Cluster 53:
 Module X experienced an invalid data format issue
        Input format mismatch occurred in module X
Module X reported an error in input format vali...
Module X failed to process input due to formatt...
Input data format in module X was invalid or co...

Cluster 52:
Service health check was not successful because...
Invalid SSL certificate resulted in a failed se...
Service health check failure was due to an inva...
An issue with the SSL certificate caused the se...
Service health check failure was caused by an e...

Cluster 18:
Boot process terminated unexpectedly due to ker...
System encountered kernel panic during initiali...
    Boot process was stopped by kernel malfunction
System encountered kernel failure during bootup...
          Boot sequence failed due to kernel panic

Cluster 25:
         System configuration is no longer valid
Configuration is corrupted throughout the system
     Cross-system configuration failure occurred
     System configuration is experiencing errors
        Configuration malfunction is system-wide

Cluster 42:
User 5127 has escalated admin privileges withou...
            User 9745 has escalated to admin level
     User 8483 escalated privileges to admin level
            User 1987 has escalated to admin level
     User 8395 escalated privileges to admin level

Cluster 59:
Potential security threat: Admin privilege esca...
    Admin privilege escalation alert for user 2893
    Admin privilege escalation alert for user 8532
Potential security threat: Admin privilege esca...
Warning: Potential admin privilege escalation f...

Cluster 26:
        Privilege elevation detected for user 5038
Elevation of admin privileges detected for user...
Elevation of admin privileges detected for user...
User 6069 has been granted elevated admin privi...
   Admin privilege elevation warning for user 7574

In [12]:
# capture each message log
import re

def classify_log_message(log_message):
  regex_patterns ={
      r"User User\d+ logged (in|out)": "User Action",
      r"Backup (started|ended) at .*": "System Notification",
      r"Backup completed successfully.": "System Notification",
      r"Backup failed with error: .*": "System Notification",
      r"System updated to version .*": "System Notification",
      r"Disk cleanup completed successfully.": "System Notification",
      r"Disk cleanup failed with error: .*": "System Notification",
      r"System reboot initiated.": "System Notification",
      r"System shutdown initiated.": "System Notification",
      r"System update initiated.": "System Notification",
      r"Account with ID .* created by .*" : "User Action",
      r"Account with ID .* deleted by .*" : "User Action",
      r"Account with ID .* updated by .*" : "User Action",
      r"Account with ID .* locked by .*" : "User Action",
      r"Account with ID .* unlocked by .*" : "User Action",
      r"Account with ID .* disabled by .*" : "User Action",
      r"Account with ID .* enabled by .*" : "User Action",
      r"Account with ID .* added to group .* by .*" : "User Action",
      r"Account with ID .* removed from group .* by .*" : "User Action",
      r"Account with ID .* added to role .* by .*" : "User Action",
      r"Account with ID .* removed from role .* by .*" : "User Action",
      r"Account with ID .* added to policy .* by .*" : "User Action",
      r"Account with ID .* removed from policy .* by .*" : "User Action"
  }

  for pattern, label in regex_patterns.items():
    if re.search(pattern, log_message, re.IGNORECASE):
      return label
  return None

In [13]:
classify_log_message("System update initiated.")

'System Notification'

In [14]:
# apply this function to log_message column
df['regex_label'] = df['log_message'].apply(classify_log_message)
df.head()

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None

In [15]:
df_non_regex = df[df.regex_label.isna()].copy()
df_non_regex.head()

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None

In [16]:
df_non_regex.shape

(1963, 7)

In [17]:
df_non_regex['target_label'].value_counts()

HTTP Status            1017
Security Alert          371
Error                   177
Resource Usage          177
Critical Error          161
System Notification      53
Workflow Error            4
Deprecation Warning       3
Name: target_label, dtype: int64

In [18]:
# for less data in workflow error and deprecation warning, we can use LLM butfirst well create embedding
df_non_legacy = df_non_regex[df_non_regex.source != 'LegacyCRM']

In [19]:
df_non_legacy.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [20]:
filtered_embeddings = model.encode(df_non_legacy['log_message'].tolist())
filtered_embeddings

array([[-0.10293962,  0.03354593, -0.02202606, ...,  0.00457791,
        -0.04259717,  0.00322621],
       [ 0.00804573, -0.03573923,  0.04938737, ...,  0.01538319,
        -0.06230948, -0.02774663],
       [-0.00908223,  0.13003924, -0.05275566, ...,  0.02014104,
        -0.05117098, -0.02930296],
       ...,
       [-0.04022264,  0.0422436 , -0.06610421, ...,  0.0236367 ,
        -0.00530877,  0.0204446 ],
       [-0.03603452,  0.01960893,  0.10052755, ...,  0.03668106,
        -0.02487851, -0.00578846],
       [ 0.01457431,  0.04911832, -0.00301354, ...,  0.01029741,
        -0.00068493,  0.00708859]], dtype=float32)

In [21]:
# logistic regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

X = filtered_embeddings
y = df_non_legacy['target_label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

report = classification_report(y_test, y_pred)
print(report)

                     precision    recall  f1-score   support

     Critical Error       0.91      1.00      0.95        29
              Error       1.00      0.91      0.95        32
        HTTP Status       1.00      1.00      1.00       217
     Resource Usage       1.00      1.00      1.00        28
     Security Alert       1.00      1.00      1.00        77
System Notification       1.00      1.00      1.00         9

           accuracy                           0.99       392
          macro avg       0.98      0.98      0.98       392
       weighted avg       0.99      0.99      0.99       392

In [23]:
import joblib
joblib.dump(model, 'model.joblib')

['model.joblib']